// English synonyms / jargon -> chapters. Each chapter's own English name (`en`) is indexed automatically;
// this table only adds *extra* ways to reach it. Add your own here: [subject, chapter `en`, [phrases...]].
import type { Subject } from '../data/types'

export const ALIASES: [Subject, string, string[]][] = [
  // Physics
  ['Phy', 'Dynamics', ['kinematics', 'motion', 'projectile', 'projectile motion', 'velocity', 'acceleration', 'gotibidda']],
  ['Phy', 'Newtonian Mechanics', ['newton', 'newton laws', 'laws of motion', 'momentum', 'collision', 'impulse', 'mechanics']],
  ['Phy', 'Work, Power & Energy', ['work', 'energy', 'power', 'work energy']],
  ['Phy', 'Gravity', ['gravitation', 'gravitational', 'satellite', 'orbit', 'escape velocity']],
  ['Phy', 'Periodic Motion', ['shm', 'simple harmonic', 'oscillation', 'pendulum', 'spring']],
  ['Phy', 'Structure Properties of Matter', ['elasticity', 'fluid', 'viscosity', 'surface tension', 'young modulus', 'hooke']],
  ['Phy', 'Wave', ['waves', 'sound', 'doppler', 'standing wave', 'beats']],
  ['Phy', 'Ideal Gas', ['kinetic theory', 'gas laws', 'boyle', 'charles', 'gas', 'gases']],
  ['Phy', 'Thermodynamics', ['heat', 'heat engine', 'entropy', 'carnot', 'first law']],
  ['Phy', 'Static Electricity', ['electrostatics', 'coulomb', 'capacitor', 'capacitance', 'gauss', 'electric field', 'potential']],
  ['Phy', 'Current Electricity', ['ohm', 'kirchhoff', 'resistance', 'wheatstone', 'circuit', 'galvanometer']],
  ['Phy', 'Magnetism', ['biot savart', 'ampere', 'magnetic effect', 'lorentz', 'magnetic field']],
  ['Phy', 'Electromagnetic Induction', ['emi', 'faraday', 'lenz', 'ac', 'alternating current', 'transformer', 'inductance', 'induction']],
  ['Phy', 'Geometrical Optics', ['optics', 'lens', 'mirror', 'refraction', 'prism', 'reflection']],
  ['Phy', 'Physical Optics', ['diffraction', 'young double slit', 'double slit', 'polarization', 'interference']],
  ['Phy', 'Modern Physics', ['relativity', 'photoelectric', 'compton', 'de broglie', 'einstein']],
  ['Phy', 'Nuclear Physics', ['nuclear', 'radioactivity', 'half life', 'atomic model', 'bohr', 'x ray', 'atom']],
  ['Phy', 'Semiconductor', ['electronics', 'diode', 'transistor', 'logic gate', 'pn junction']],
  ['Phy', 'Astronomy', ['star', 'stars', 'galaxy', 'planet']],
  ['Phy', 'Physical World & Measurement', ['measurement', 'dimension', 'units', 'error', 'significant figures']],
  ['Phy', 'Vector', ['vectors', 'dot product', 'cross product', 'scalar']],
  // Chemistry
  ['Chem', 'Quantitative Chemistry', ['stoichiometry', 'mole', 'molarity', 'normality', 'titration', 'redox', 'concentration']],
  ['Chem', 'Organic Chemistry', ['organic', 'hydrocarbon', 'alkane', 'alkene', 'alkyne', 'benzene', 'functional group', 'cannizzaro']],
  ['Chem', 'Qualitative Chemistry', ['salt analysis', 'flame test', 'ions', 'radical']],
  ['Chem', 'Periodic Properties & Chemical Bonding', ['periodic table', 'bonding', 'chemical bond', 'vsepr', 'hybridization', 'periodic']],
  ['Chem', 'Chemical Change', ['equilibrium', 'thermochemistry', 'reaction rate', 'kinetics', 'le chatelier', 'ksp', 'kp', 'kc', 'enthalpy']],
  ['Chem', 'Electrochemistry', ['galvanic', 'electrolysis', 'emf', 'nernst', 'cell', 'electrode']],
  ['Chem', 'Environmental Chemistry', ['environment', 'pollution', 'ozone', 'greenhouse', 'water']],
  // Math
  ['Math', 'Matrix', ['matrices', 'determinant', 'inverse matrix']],
  ['Math', 'Vector (Math)', ['vectors', 'dot product', 'cross product']],
  ['Math', 'Straight Line', ['line', 'lines', 'slope', 'coordinate geometry']],
  ['Math', 'Circle', ['circles', 'tangent', 'coordinate geometry']],
  ['Math', 'Conics', ['conic', 'parabola', 'ellipse', 'hyperbola', 'coordinate geometry']],
  ['Math', 'Permutation & Combination', ['permutation', 'combination', 'pnc', 'arrangement']],
  ['Math', 'Trigonometry', ['trig', 'trigonometric', 'compound angle', 'sin cos tan']],
  ['Math', 'Inverse Trigonometry', ['inverse trig', 'inverse trigonometric', 'arcsin', 'sin inverse', 'trigonometric equation']],
  ['Math', 'Function', ['functions', 'domain', 'range', 'graph']],
  ['Math', 'Differentiation', ['derivative', 'derivatives', 'calculus', 'limit', 'limits', 'differential']],
  ['Math', 'Integration', ['integral', 'integrals', 'calculus', 'definite integral']],
  ['Math', 'Complex Number', ['complex', 'argand', 'imaginary', 'polar form']],
  ['Math', 'Polynomial', ['polynomials', 'roots', 'quadratic', 'equation', 'cubic']],
  ['Math', 'Statics', ['lami', 'lami theorem', 'equilibrium of forces', 'resultant', 'friction']],
  ['Math', 'Motion in Plane', ['projectile', 'kinematics in plane', 'particle motion']],
  ['Math', 'Binomial Expansion', ['binomial', 'binomial theorem', 'expansion']],
  ['Math', 'Probability', ['chance', 'bayes', 'probability']],
  ['Math', 'Statistics', ['dispersion', 'variance', 'standard deviation', 'sd', 'mean']],
  ['Math', 'Linear Programming', ['lpp', 'linear program', 'optimization']],
  ['Math', 'Real Number', ['inequality', 'inequalities', 'modulus', 'absolute value']],
]
